# .pre-commit-config.yml
repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0  # Specify the version installed - as seen inside the requirements.txt file
    hooks:
      - id: black
        args: ['--line-length', '100']  # Optional: Set the line length for black

-   repo: https://github.com/PyCQA/pylint
    rev: v3.3.7  # Specify the version installed - as seen inside the requirements.txt file
    hooks:
      - id: pylint
