version: "3.8"

services:
  # PostgreSQL for Development
  postgres_dev:
    image: postgres:17
    container_name: fdbt_pg__dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: your-user-name
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: fast_django_backend_template__db_dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  # PostgreSQL for Staging (for local testing only. Recommendation: Use a managed postgres service for staging and prod)  
  postgres_staging:
    image: postgres:17
    container_name: fdbt_pg__staging
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: your-user-name
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: fast_django_backend_template__db_staging
    volumes:
      - pgdata_staging:/var/lib/postgresql/data

  # PostgreSQL for Production (for local testing only. Recommendation: Use a managed postgres service for staging and prod)
  postgres_prod:
    image: postgres:17
    container_name: fdbt_pg__prod
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: your-user-name
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: fast_django_backend_template__db_prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    # Comment or remove if using real prod DBs

volumes:
  pgdata_dev:
  pgdata_staging:
  pgdata_prod:
